# Generated by Django 2.2 on 2022-04-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220430_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='time_created',
            field=models.DateField(auto_now=True),
        ),
    ]
